""" urls under /dev/ space """

from django.conf.urls import url
from .views import (
    DevView,
    RoleDetailView,
    RoleCreateView,
    RoleUpdateView,
    RoleListView,
    LogicalGroupCreateView,
    LogicalGroupDetailView,
    LogicalGroupUpdateView,
    LogicalGroupListView,
    ConfigSectionCreateView,
    ConfigSectionDetailView,
    ConfigSectionUpdateView,
    ConfigSectionListView,
    RoleTaskCreateView,
    RoleTaskDetailView,
    RoleTaskUpdateView,
    RoleTaskListView,
    ApiCreateView,
    ApiDetailView,
    ApiUpdateView,
    ApiListView,
    ApiSectionCreateView,
    ApiSectionDetailView,
    ApiSectionUpdateView,
    ApiSectionListView,
    ConfigSubDetailView,
    ConfigSubCreateView,
    ConfigSubUpdateView,
    ConfigSubListView,
    ApiSubDetailView,
    ApiSubCreateView,
    ApiSubUpdateView,
    ApiSubListView,
    RoleTemplateDetailView,
    RoleTemplateCreateView,
    RoleTemplateUpdateView,
    RoleTemplateListView,
)


urlpatterns = [
    url(r'^$', DevView.as_view(), name='index'),
    url(r'^role/create/$', RoleCreateView.as_view(), name='createrole'),
    url(r'^role/(?P<slug>[\w-]+)/$', RoleDetailView.as_view(), name='getrole'),
    url(r'^role/(?P<slug>[\w-]+)/edit/$', RoleUpdateView.as_view(), name='editrole'),
    url(r'^role/$', RoleListView.as_view(), name='listrole'),
    url(r'^logicalgroup/create/$', LogicalGroupCreateView.as_view(), name='createlogicalgroup'),
    url(r'^logicalgroup/(?P<slug>[\w-]+)/$', LogicalGroupDetailView.as_view(), name='getlogicalgroup'),
    url(r'^logicalgroup/(?P<slug>[\w-]+)/edit/$', LogicalGroupUpdateView.as_view(), name='editlogicalgroup'),
    url(r'^logicalgroup/$', LogicalGroupListView.as_view(), name='listlogicalgroup'),
    url(r'^configsection/create/$', ConfigSectionCreateView.as_view(), name='createconfigsection'),
    url(r'^configsection/(?P<slug>[\w-]+)/$', ConfigSectionDetailView.as_view(), name='getconfigsection'),
    url(r'^configsection/(?P<slug>[\w-]+)/edit/$', ConfigSectionUpdateView.as_view(), name='editconfigsection'),
    url(r'^configsection/$', ConfigSectionListView.as_view(), name='listconfigsection'),
    url(r'^roletask/create/$', RoleTaskCreateView.as_view(), name='createroletask'),
    url(r'^roletask/(?P<slug>[\w-]+)/$', RoleTaskDetailView.as_view(), name='getroletask'),
    url(r'^roletask/(?P<slug>[\w-]+)/edit/$', RoleTaskUpdateView.as_view(), name='editroletask'),
    url(r'^roletask/$', RoleTaskListView.as_view(), name='listroletask'),
    url(r'^api/create/$', ApiCreateView.as_view(), name='createapi'),
    url(r'^api/(?P<slug>[\w-]+)/$', ApiDetailView.as_view(), name='getapi'),
    url(r'^api/(?P<slug>[\w-]+)/edit/$', ApiUpdateView.as_view(), name='editapi'),
    url(r'^api/$', ApiListView.as_view(), name='listapi'),
    url(r'^apisection/create/$', ApiSectionCreateView.as_view(), name='createapisection'),
    url(r'^apisection/(?P<slug>[\w-]+)/$', ApiSectionDetailView.as_view(), name='getapisection'),
    url(r'^apisection/(?P<slug>[\w-]+)/edit/$', ApiSectionUpdateView.as_view(), name='editapisection'),
    url(r'^apisection/$', ApiSectionListView.as_view(), name='listapisection'),
    url(r'^configsub/create/$', ConfigSubCreateView.as_view(), name='createconfigsub'),
    url(r'^configsub/(?P<slug>[\w-]+)/$', ConfigSubDetailView.as_view(), name='getconfigsub'),
    url(r'^configsub/(?P<slug>[\w-]+)/edit/$', ConfigSubUpdateView.as_view(), name='editconfigsub'),
    url(r'^configsub/$', ConfigSubListView.as_view(), name='listconfigsub'),
    url(r'^apisub/create/$', ApiSubCreateView.as_view(), name='createapisub'),
    url(r'^apisub/(?P<slug>[\w-]+)/$', ApiSubDetailView.as_view(), name='getapisub'),
    url(r'^apisub/(?P<slug>[\w-]+)/edit/$', ApiSubUpdateView.as_view(), name='editapisub'),
    url(r'^apisub/$', ApiSubListView.as_view(), name='listapisub'),
    url(r'^roletemplate/create/$', RoleTemplateCreateView.as_view(), name='createroletemplate'),
    url(r'^roletemplate/(?P<slug>[\w-]+)/$', RoleTemplateDetailView.as_view(), name='getroletemplate'),
    url(r'^roletemplate/(?P<slug>[\w-]+)/edit/$', RoleTemplateUpdateView.as_view(), name='editroletemplate'),
    url(r'^roletemplate/$', RoleTemplateListView.as_view(), name='listroletemplate'),
]