# Generated by Django 2.0 on 2017-12-17 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicContrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=32)),
                ('exid', models.CharField(max_length=16, null=True)),
                ('desc', models.CharField(max_length=64, null=True)),
                ('addon', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('ispublic', models.BooleanField(default=False)),
                ('popularity', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
