# Generated by Django 2.0 on 2017-12-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publiccontrib',
            name='addon',
        ),
    ]
