# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisectionobject',
            name='exid',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='apisubobject',
            name='exid',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='apivalueobject',
            name='exid',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='configsectionobject',
            name='exid',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='configsubobject',
            name='exid',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='configvalueobject',
            name='exid',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='logicalgroupobject',
            name='exid',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='roleobject',
            name='exid',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
