# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extender', '0004_apisubobject_trailngspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisectionobject',
            name='docurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
