# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extender', '0006_apisubobject_configsubobject_roletemplateobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apisubobject',
            name='api',
        ),
        migrations.RemoveField(
            model_name='configsubobject',
            name='api',
        ),
        migrations.RemoveField(
            model_name='roletemplateobject',
            name='exid',
        ),
        migrations.AddField(
            model_name='apisubobject',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extender.ApiSectionObject'),
        ),
        migrations.AddField(
            model_name='configsubobject',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extender.ConfigSectionObject'),
        ),
        migrations.AddField(
            model_name='roletemplateobject',
            name='desc',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='roletemplateobject',
            name='istemplate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roletemplateobject',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extender.RoleObject'),
        ),
    ]
