# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extender', '0007_auto_20171209_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiValueObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=32)),
                ('exid', models.CharField(max_length=8, null=True)),
                ('desc', models.CharField(max_length=64, null=True)),
                ('addon', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigValueObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=32)),
                ('exid', models.CharField(max_length=8, null=True)),
                ('desc', models.CharField(max_length=64, null=True)),
                ('addon', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
