# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extender', '0008_apivalueobject_configvalueobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apivalueobject',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='apivalueobject',
            name='shortname',
        ),
        migrations.RemoveField(
            model_name='configvalueobject',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='configvalueobject',
            name='shortname',
        ),
        migrations.AddField(
            model_name='apivalueobject',
            name='subobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extender.ApiSubObject'),
        ),
        migrations.AddField(
            model_name='apivalueobject',
            name='value',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='configvalueobject',
            name='subobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extender.ConfigSubObject'),
        ),
        migrations.AddField(
            model_name='configvalueobject',
            name='value',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
